### ISSUE TITLE
Can't access original photo through web UI, can only access thumbnail

### ISSUE THREAD

**Issue by yassendobrev** [LibrePhotos/librephotos#603]
## 🐛 Bug Report

[ ] I am including my log files in zip format.
[*] I have looked for similar issues among all the former issues including closed ones.

### What Operating system and version is LibrePhotos running on:
64-bit Raspberry Pi OS 11

### What architecture is LibrePhotos running on:
ARM

### How is LibrePhotos installed:
Docker

### If running via Docker or Kubernetes please list version including docker-compose:
Docker version 20.10.17, build 100c701
Docker Compose version v2.6.0

### Are you running LibrePhotos on a virtual machine if so please list:
No

### How is you picture library mounted on the host (or in the virtual machine):
Local file system (ext4), using NextClouds's `InstantUpload/Camera` directory.

### Description of issue:
Scanning for photos and thumbnail generation works as expected. However, I can't access the original full-size photos through the web interface.

If I click on a photo and then on the 🛈 icon, under `File Path` I see a link with text which looks like `/data/USERNAME/files/InstantUpload/Camera/PHOTO_NAME.jpg` which is the correct path of the NextCloud directory relative to the `scanDirectory`. The link however points to `media/photos/THUMBNAIL_NAME.jpg` and if I follow it I get a `403 Forbidden` error.

I can successfully access the thumbnail itself at `media/square_thumbnails/THUMBNAIL_NAME`. I don't see a directory `photos` under `data/protected_media`.

My settings in `.env` are
```
scanDirectory=/home/USER/www/nextcloud/data
data=/home/USER/librephotos/data
```

### How can we reproduce it:
Can you confirm that no additional configuration steps are needed to set `scanDirectory` to another photo on the file system?

**Comment by ippocratis** [comment]
Folder/file permission maybe?
In my case that was it

**Comment by derneuere** [comment]
This bug is already fixed on dev, I think. If you want to test that, you can always check out the demo, which is on dev. We didn't do a release in a while, but I will do one in the next week :)

**Comment by yassendobrev** [comment]
Thanks for the fast responses!

@ippocratis The docker container runs as root and also it looks like it can read the photos, because it successfully generates the thumbnails. Does it need write permissions?

@derneuere I switched to the `dev` tag for the backend, frontend, and proxy docker images which were last updated on Aug 10, but I still get the same behavior. Is the demo configuration available somewhere for me to compare to my config? Also, what is the expected behavior for the original photos - should they be copied somewhere or should a symlink be created? How are they being accessed by the web UI?

**Comment by ippocratis** [comment]
@yassendobrev 
As of https://docs.librephotos.com/1/standard_install/
change the permission to allow read/write/exectute for others of your photos folder.

**Comment by ippocratis** [comment]
Btw I'd love to see a way to workaround this
I don't like  rwx Perm to "others"

**Comment by yassendobrev** [comment]
@ippocratis it worked! Thank you!!

**Comment by derneuere** [comment]
Why was this reopened? :sweat_smile:

**Comment by yassendobrev** [comment]
@derneuere sorry I got carried away and forgot to describe my problem.

@ippocratis I tried using `setfacl` to set the default permissions to new files, but this doesn't work for the execute file permission (from the `setfacl` documentation: `execute only if the file is a directory or already has execute permission for some user (X).`). 

I use `inotify` to rescan the library when new photos are added and I could add setting the `o+x` permission there, but I wonder if you found a more elegant approach.

**Comment by ippocratis** [comment]
My workaround is simpler

I have an "import" folder where I move photos from various family phones etc
Then I use cron and exiftool to move and short those in to my library
Later again with cron I change their permissions and copy them to a second external drive
And finally again with cron I scan the library  with librephotos

Inotify is more legit I think as its based at events rather than time based scripts with cron
Exif script:
```
sudo /usr/bin/site_perl/exiftool '-Directory<CreateDate' -d /run/media/ippo/TOSHIBA/photos/%Y/%m  /run/media/ippo/TOSHIBA/photoimport;
```
Cronjobs:
```
05 3 * * * bash /home/ippo/photos-exif.sh
30 3 * * * sudo chmod 777 -R /run/media/ippo/TOSHIBA/photos
40 3 * * * sudo rsync -aP /run/media/ippo/TOSHIBA/photos/ /run/media/ippo/700C216E0C213110/photos
59 3 * * * sudo docker exec --user root librephotos-docker-backend-1 python3 manage.py scan >/dev/null 2>&1
```
